package protege_generated.impl;

import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.*;
import protege_generated.Job;
import protege_generated.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Job
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public class DefaultJob extends AbstractWrappedInstance
         implements Job {

    public DefaultJob(Instance instance) {
        super(instance);
    }


    public DefaultJob() {
    }

    // Slot organization

    public String getOrganization() {
        return (String) getWrappedProtegeInstance().getOwnSlotValue(getOrganizationSlot());
    }


    public Slot getOrganizationSlot() {
        final String name = "organization";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasOrganization() {
        return hasSlotValues(getOrganizationSlot());
    }


    public void setOrganization(String newOrganization) {
        setSlotValue(getOrganizationSlot(), newOrganization);
    }

    // Slot position

    public String getPosition() {
        return (String) getWrappedProtegeInstance().getOwnSlotValue(getPositionSlot());
    }


    public Slot getPositionSlot() {
        final String name = "position";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasPosition() {
        return hasSlotValues(getPositionSlot());
    }


    public void setPosition(String newPosition) {
        setSlotValue(getPositionSlot(), newPosition);
    }

    // Slot salary

    public int getSalary() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getSalarySlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getSalarySlot() {
        final String name = "salary";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasSalary() {
        return hasSlotValues(getSalarySlot());
    }


    public void setSalary(int newSalary) {
        setSlotValue(getSalarySlot(), new java.lang.Integer(newSalary));
    }
}
