package protege_generated.impl;

import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.*;
import protege_generated.Case;
import protege_generated.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Case
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public class DefaultCase extends AbstractWrappedInstance
         implements Case {

    public DefaultCase(Instance instance) {
        super(instance);
    }


    public DefaultCase() {
    }

    // Slot client

    public Client getClient() {
        Object object = getWrappedProtegeInstance().getOwnSlotValue(getClientSlot());
        Cls cls = getKnowledgeBase().getCls("Client");
        if (object instanceof Instance && ((Instance)object).hasType(cls)) {
            return new DefaultClient((Instance)object);
        }
        return null;
    }


    public Slot getClientSlot() {
        final String name = "client";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasClient() {
        return hasSlotValues(getClientSlot());
    }


    public void setClient(Client newClient) {
        setSlotValue(getClientSlot(), newClient);
    }

    // Slot credit

    public CreditData getCredit() {
        Object object = getWrappedProtegeInstance().getOwnSlotValue(getCreditSlot());
        Cls cls = getKnowledgeBase().getCls("CreditData");
        if (object instanceof Instance && ((Instance)object).hasType(cls)) {
            return new DefaultCreditData((Instance)object);
        }
        return null;
    }


    public Slot getCreditSlot() {
        final String name = "credit";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasCredit() {
        return hasSlotValues(getCreditSlot());
    }


    public void setCredit(CreditData newCredit) {
        setSlotValue(getCreditSlot(), newCredit);
    }

    // Slot decisionSPR

    public String getDecisionSPR() {
        return (String) getWrappedProtegeInstance().getOwnSlotValue(getDecisionSPRSlot());
    }


    public Slot getDecisionSPRSlot() {
        final String name = "decisionSPR";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasDecisionSPR() {
        return hasSlotValues(getDecisionSPRSlot());
    }


    public void setDecisionSPR(String newDecisionSPR) {
        setSlotValue(getDecisionSPRSlot(), newDecisionSPR);
    }
}
