package protege_generated.impl;

import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.*;
import protege_generated.CreditData;
import protege_generated.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: CreditData
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public class DefaultCreditData extends AbstractWrappedInstance
         implements CreditData {

    public DefaultCreditData(Instance instance) {
        super(instance);
    }


    public DefaultCreditData() {
    }

    // Slot expense

    public int getExpense() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getExpenseSlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getExpenseSlot() {
        final String name = "expense";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasExpense() {
        return hasSlotValues(getExpenseSlot());
    }


    public void setExpense(int newExpense) {
        setSlotValue(getExpenseSlot(), new java.lang.Integer(newExpense));
    }

    // Slot income

    public int getIncome() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getIncomeSlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getIncomeSlot() {
        final String name = "income";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasIncome() {
        return hasSlotValues(getIncomeSlot());
    }


    public void setIncome(int newIncome) {
        setSlotValue(getIncomeSlot(), new java.lang.Integer(newIncome));
    }

    // Slot sum

    public int getSum() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getSumSlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getSumSlot() {
        final String name = "sum";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasSum() {
        return hasSlotValues(getSumSlot());
    }


    public void setSum(int newSum) {
        setSlotValue(getSumSlot(), new java.lang.Integer(newSum));
    }

    // Slot term

    public int getTerm() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getTermSlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getTermSlot() {
        final String name = "term";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasTerm() {
        return hasSlotValues(getTermSlot());
    }


    public void setTerm(int newTerm) {
        setSlotValue(getTermSlot(), new java.lang.Integer(newTerm));
    }
}
