package protege_generated;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Case
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public interface Case {

    // Slot client

    Client getClient();

    boolean hasClient();

    void setClient(Client newClient);


    // Slot credit

    CreditData getCredit();

    boolean hasCredit();

    void setCredit(CreditData newCredit);


    // Slot decisionSPR

    String getDecisionSPR();

    boolean hasDecisionSPR();

    void setDecisionSPR(String newDecisionSPR);

    void delete();
}
