package protege_generated;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Client
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public interface Client {

    // Slot age

    int getAge();

    boolean hasAge();

    void setAge(int newAge);


    // Slot document

    Document getDocument();

    boolean hasDocument();

    void setDocument(Document newDocument);


    // Slot fullName

    String getFullName();

    boolean hasFullName();

    void setFullName(String newFullName);


    // Slot inBlackList

    boolean getInBlackList();

    boolean hasInBlackList();

    void setInBlackList(boolean newInBlackList);


    // Slot job

    Job getJob();

    boolean hasJob();

    void setJob(Job newJob);


    // Slot phone

    String getPhone();

    boolean hasPhone();

    void setPhone(String newPhone);


    // Slot registration

    boolean getRegistration();

    boolean hasRegistration();

    void setRegistration(boolean newRegistration);

    void delete();
}
