package protege_generated;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: CreditData
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public interface CreditData {

    // Slot expense

    int getExpense();

    boolean hasExpense();

    void setExpense(int newExpense);


    // Slot income

    int getIncome();

    boolean hasIncome();

    void setIncome(int newIncome);


    // Slot sum

    int getSum();

    boolean hasSum();

    void setSum(int newSum);


    // Slot term

    int getTerm();

    boolean hasTerm();

    void setTerm(int newTerm);

    void delete();
}
