package protege_generated;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Document
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public interface Document {

    // Slot number

    int getNumber();

    boolean hasNumber();

    void setNumber(int newNumber);


    // Slot seria

    int getSeria();

    boolean hasSeria();

    void setSeria(int newSeria);


    // Slot type

    String getType();

    boolean hasType();

    void setType(String newType);


    // Slot valid

    boolean getValid();

    boolean hasValid();

    void setValid(boolean newValid);

    void delete();
}
