package protege_generated;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Job
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public interface Job {

    // Slot organization

    String getOrganization();

    boolean hasOrganization();

    void setOrganization(String newOrganization);


    // Slot position

    String getPosition();

    boolean hasPosition();

    void setPosition(String newPosition);


    // Slot salary

    int getSalary();

    boolean hasSalary();

    void setSalary(int newSalary);

    void delete();
}
