package protege_generated;

import protege_generated.impl.*;
import edu.stanford.smi.protege.code.generator.wrapping.OntologyJavaMappingUtil;

/**
 * Generated by Protege (http://protege.stanford.edu).
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public class OntologyJavaMapping {

    public static void initMap() {
        OntologyJavaMappingUtil.add("Case", Case.class, DefaultCase.class);
        OntologyJavaMappingUtil.add("Client", Client.class, DefaultClient.class);
        OntologyJavaMappingUtil.add("CreditData", CreditData.class, DefaultCreditData.class);
        OntologyJavaMappingUtil.add("Document", Document.class, DefaultDocument.class);
        OntologyJavaMappingUtil.add("Job", Job.class, DefaultJob.class);
        OntologyJavaMappingUtil.add("Requirements", Requirements.class, DefaultRequirements.class);
    }
}
