package protege_generated;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Requirements
 *
 * @version generated on Fri Mar 25 01:08:40 MSK 2016
 */
public interface Requirements {

    // Slot cond

    String getCond();

    boolean hasCond();

    void setCond(String newCond);


    // Slot slotName

    String getSlotName();

    boolean hasSlotName();

    void setSlotName(String newSlotName);


    // Slot value

    String getValue();

    boolean hasValue();

    void setValue(String newValue);

    void delete();
}
